version: '3'
services:
    front-abcc_article:
        container_name: abcc_article-frontend
        build: ../abcc-article-frontend
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ../abcc-article-frontend:/abcc_article-frontend

    flask-abcc_article-api:
        container_name: abcc_article-api
        build: ../abcc-article-api-rest/app
        restart: always
        ports:
            - '8000:5000'
        volumes:
            - ../abcc-article-api-rest/app:/app
        networks:
            - abcc_article_net
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_HOST: mysql_abcc_article_db
            MYSQL_PORT: 3306
            MYSQL_DATABASE: abcc_article

    mysql-abcc_article-db:
        container_name: mysql_abcc_article_db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: abcc_article
        ports:
            - '3308:3306'
        volumes:
            - ../abcc-article-api-rest/db/database:/var/lib/mysql
        networks:
            - abcc_article_net

networks:
    abcc_article_net:

volumes:
    app:
    database: